The hook "displayProductButtons" is deprecated
PrestaShop/ps_sharebuttons pull request #55
Opened 2022-07-28 08:31 UTC by leemyongpakvn

use "displayProductAdditionalInfo" instead

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The hook "displayProductButtons" is deprecated, and need to be replaced by "displayProductAdditionalInfo"
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#29189.
| How to test?  | Please follow above issue's Step to reproduce before and after PR. Do not forget to **Reset** module in Back-office after PR.

2022-07-28 08:51 UTC, okom3pom commented
Hello @leemyongpakvn can you add an upgrade file with unregisterhook('displayProductButtons')

2022-07-28 09:10 UTC, PrestaEdit requested changes
As @okom3pom said, you need to add the upgrade file to unregist/register the hook.

2022-07-28 09:42 UTC, leemyongpakvn commented
@okom3pom n @PrestaEdit I did not see the upgrade directory so I thought this module is an exception. The upgrade file is uploaded now but I don't know how to create upgrade directory here :(

2022-07-29 09:04 UTC, okom3pom commented on upgrade/install-2.1.2.php
> +    return $object->unregisterHook('displayProductButtons')
```suggestion
    return $object->unregisterHook('displayProductButtons')
```

2022-07-29 09:28 UTC, okom3pom commented
When the issue is ok for QA i approve

2022-08-02 17:48 UTC, okom3pom approved these changes

2022-09-01 16:17 UTC, matks approved these changes

2022-09-12 12:12 UTC, florine2623 approved these changes
Hello @leemyongpakvn ,

Thanks for the PR!

Tested and approved.
No more deprecate message is shown.
Position of the module is correct.

It is QA ✅

2022-09-12 14:32 UTC, matthieu-rolland commented
thank you @leemyongpakvn and @florine2623 !

2022-09-12 14:32 UTC, merged